version: '3.3'
services:

  zookeeper:
    image: zookeeper:3.5

  kafka:
    image: confluentinc/cp-kafka:5.2
    environment:
      ZOOKEEPER_IP: "zookeeper"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zerospike:
    image: jacamars/zerospike:v1
    environment:
      BROKERLIST: "kafka:9092"
    depends_on:
      - kafka
    command: bash -c "sleep 5 && ./wait-for-it.sh kafka:9092 -t 120 && sleep 1; ./zerospike"

  bidder:
    image: jacamars/adnexus:v1
    environment:
      BROKERLIST: "kafka:9092"
      PUBSUB: "zerospike"
      EXTERNAL: "http://localhost"
      ADMINPORT: "0"
      ACCOUNTING: "accountingsystem"
      FREQGOV: "false"
      INDEXPAGE: "/index.html"
    ports:
      - "80:8080"
      - "8155:8155"
    depends_on:
      - kafka
      - zerospike
    command: bash -c "sleep 5 && ./wait-for-it.sh kafka:9092 -t 120 && ./wait-for-it.sh zerospike:6000 -t 120 && sleep 1; ./adnexus"

  crosstalk:
    image: jacamars/crosstalk:v1
    environment:
      REGION: "US"
      GHOST: "elastic1"
      AHOST: "elastic1"
      BROKERLIST: "kafka:9092"
      PUBSUB: "zerospike"
      CONTROL: "8100"
      JDBC: "jdbc:mysql://mysql/adnexus?user=adnexus&password=adnexus"
      PASSWORD: "adnexus"
    depends_on:
      - kafka
      - zerospike

  mysql:
    image: adnexus/mysql-demo
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=adnexus
      - MYSQL_DATABASE=adnexus
      - MYSQL_USER=adnexus
      - MYSQL_PASSWORD=adnexus

  web:
    image: ploh/rtbadmin_open
    command: bash -c "./wait_for_it.sh mysql:3306 --timeout=120; bundle exec rails s -p 3000 -b '0.0.0.0' -e development"
    ports:
      - "3000:3000"
    environment:
      - CUSTOMER_NAME=ADNEXUS
      - ADNEXUS_DATABASE_HOST=mysql
      - ADNEXUS_DATABASE_PORT=3306
      - ADNEXUS_DATABASE_USERNAME=adnexus
      - ADNEXUS_DATABASE_PASSWORD=adnexus
      - ADNEXUS_DATABASE_NAME=adnexus
      - ELASTICSEARCH_ENABLE=true
      - ELASTICSEARCH_HOST=elastic1:9200
      - ELASTICSEARCH_KIBANA_URL=http://kibana:5601/
      - RTB_CROSSTALK_REGION_HOSTS={"US" => "crosstalk"}
      - RTB_CROSSTALK_PORT=8100
      - RTB_CROSSTALK_USER=adnexus
      - RTB_CROSSTALK_PASSWORD=adnexus

  elastic:
    image: ploh/elastic_pwd
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  logstash:
    image: ploh/logstash_pwd
    environment:
      - "XPACK_MONITORING_ELASTICSEARCH_URL=http://elastic1:9200"
      - "XPACK_MONITORING_ENABLED=true"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    environment:
      - SERVER_NAME=elastic1
      - ELASTICSEARCH_URL=http://elastic1:9200
    ports:
      - "5601:5601"

  simulator:
    image: jacamars/adnexus:v1
    environment:
      BIDDER: "bidder:8080"
      WIN:    "10"
      PIXEL:  "95"
      CLICK:  "2"
      SLEEP:  "100"
    command: bash -c "./wait-for-it.sh bidder:8080 -t 120 && sleep 60;  ./load-elastic -host $$BIDDER -win $$WIN -pixel $$PIXEL -click $$CLICK -sleep $$SLEEP"

volumes:
  db_data: {}
